version: '2'

services:
  elasticsearch:
    build: docker/elasticsearch
    container_name: search-elastic
    environment:
      - cluster.name=search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - SERVICE_9200_NAME=elasticsearch
    hostname: search-elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    tty: true
    networks:
      - esnet
volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge