version: '2'

services:
  elasticsearch:
    image: e96tech/elasticsearch:master
    container_name: search-elastic
    environment:
      - cluster.name=search
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - SERVICE_9200_NAME=elasticsearch
    hostname: search-elastic
    tty: true
    networks:
      - esnet
volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge